// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hostconfig.proto

package hostconfig

import (
	bytes "bytes"
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ErrorInfo_ErrorType int32

const (
	UNKNOWN     ErrorInfo_ErrorType = 0
	NOT_FOUND   ErrorInfo_ErrorType = 1
	READ_FAILED ErrorInfo_ErrorType = 2
)

var ErrorInfo_ErrorType_name = map[int32]string{
	0: "UNKNOWN",
	1: "NOT_FOUND",
	2: "READ_FAILED",
}

var ErrorInfo_ErrorType_value = map[string]int32{
	"UNKNOWN":     0,
	"NOT_FOUND":   1,
	"READ_FAILED": 2,
}

func (ErrorInfo_ErrorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_031ae942b020a237, []int{3, 0}
}

type HostConfigRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *HostConfigRequest) Reset()      { *m = HostConfigRequest{} }
func (*HostConfigRequest) ProtoMessage() {}
func (*HostConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_031ae942b020a237, []int{0}
}
func (m *HostConfigRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HostConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HostConfigRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HostConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostConfigRequest.Merge(m, src)
}
func (m *HostConfigRequest) XXX_Size() int {
	return m.Size()
}
func (m *HostConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HostConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HostConfigRequest proto.InternalMessageInfo

func (m *HostConfigRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HostConfigResponse struct {
	// Types that are valid to be assigned to Result:
	//
	//	*HostConfigResponse_File
	//	*HostConfigResponse_Error
	Result isHostConfigResponse_Result `protobuf_oneof:"result"`
}

func (m *HostConfigResponse) Reset()      { *m = HostConfigResponse{} }
func (*HostConfigResponse) ProtoMessage() {}
func (*HostConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_031ae942b020a237, []int{1}
}
func (m *HostConfigResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HostConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HostConfigResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HostConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostConfigResponse.Merge(m, src)
}
func (m *HostConfigResponse) XXX_Size() int {
	return m.Size()
}
func (m *HostConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HostConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HostConfigResponse proto.InternalMessageInfo

type isHostConfigResponse_Result interface {
	isHostConfigResponse_Result()
	Equal(interface{}) bool
	MarshalTo([]byte) (int, error)
	Size() int
}

type HostConfigResponse_File struct {
	File *FileContent `protobuf:"bytes,1,opt,name=file,proto3,oneof" json:"file,omitempty"`
}
type HostConfigResponse_Error struct {
	Error *ErrorInfo `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (*HostConfigResponse_File) isHostConfigResponse_Result()  {}
func (*HostConfigResponse_Error) isHostConfigResponse_Result() {}

func (m *HostConfigResponse) GetResult() isHostConfigResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *HostConfigResponse) GetFile() *FileContent {
	if x, ok := m.GetResult().(*HostConfigResponse_File); ok {
		return x.File
	}
	return nil
}

func (m *HostConfigResponse) GetError() *ErrorInfo {
	if x, ok := m.GetResult().(*HostConfigResponse_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*HostConfigResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*HostConfigResponse_File)(nil),
		(*HostConfigResponse_Error)(nil),
	}
}

type FileContent struct {
	Content []byte `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Path    string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (m *FileContent) Reset()      { *m = FileContent{} }
func (*FileContent) ProtoMessage() {}
func (*FileContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_031ae942b020a237, []int{2}
}
func (m *FileContent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FileContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FileContent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FileContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileContent.Merge(m, src)
}
func (m *FileContent) XXX_Size() int {
	return m.Size()
}
func (m *FileContent) XXX_DiscardUnknown() {
	xxx_messageInfo_FileContent.DiscardUnknown(m)
}

var xxx_messageInfo_FileContent proto.InternalMessageInfo

func (m *FileContent) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *FileContent) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type ErrorInfo struct {
	Type    ErrorInfo_ErrorType `protobuf:"varint,1,opt,name=type,proto3,enum=dagger.hostconfig.ErrorInfo_ErrorType" json:"type,omitempty"`
	Message string              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *ErrorInfo) Reset()      { *m = ErrorInfo{} }
func (*ErrorInfo) ProtoMessage() {}
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_031ae942b020a237, []int{3}
}
func (m *ErrorInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ErrorInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ErrorInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ErrorInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorInfo.Merge(m, src)
}
func (m *ErrorInfo) XXX_Size() int {
	return m.Size()
}
func (m *ErrorInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorInfo proto.InternalMessageInfo

func (m *ErrorInfo) GetType() ErrorInfo_ErrorType {
	if m != nil {
		return m.Type
	}
	return UNKNOWN
}

func (m *ErrorInfo) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("dagger.hostconfig.ErrorInfo_ErrorType", ErrorInfo_ErrorType_name, ErrorInfo_ErrorType_value)
	proto.RegisterType((*HostConfigRequest)(nil), "dagger.hostconfig.HostConfigRequest")
	proto.RegisterType((*HostConfigResponse)(nil), "dagger.hostconfig.HostConfigResponse")
	proto.RegisterType((*FileContent)(nil), "dagger.hostconfig.FileContent")
	proto.RegisterType((*ErrorInfo)(nil), "dagger.hostconfig.ErrorInfo")
}

func init() { proto.RegisterFile("hostconfig.proto", fileDescriptor_031ae942b020a237) }

var fileDescriptor_031ae942b020a237 = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xbd, 0x8e, 0xda, 0x40,
	0x10, 0xc7, 0x77, 0x11, 0x81, 0x78, 0x9c, 0x0f, 0xb3, 0x15, 0x8a, 0xa2, 0x55, 0x64, 0xe5, 0xab,
	0x72, 0x41, 0x28, 0xa2, 0xa4, 0x09, 0x9f, 0x01, 0x25, 0x32, 0xd2, 0x0a, 0x12, 0x29, 0x0d, 0x72,
	0x60, 0x31, 0x48, 0xe0, 0x75, 0xbc, 0x4b, 0x41, 0x97, 0x3a, 0x55, 0xfa, 0x7b, 0x81, 0x7b, 0x94,
	0x2b, 0x29, 0x29, 0x0f, 0xd3, 0x5c, 0xc9, 0x23, 0x9c, 0xbc, 0x86, 0x03, 0x09, 0x74, 0xd7, 0xfd,
	0x47, 0xf3, 0x9b, 0xf9, 0xcf, 0xec, 0x2c, 0x58, 0x63, 0x21, 0xd5, 0x40, 0x04, 0xa3, 0x89, 0xef,
	0x84, 0x91, 0x50, 0x82, 0x14, 0x86, 0x9e, 0xef, 0xf3, 0xc8, 0x39, 0x24, 0xec, 0x77, 0x50, 0x68,
	0x09, 0xa9, 0x6a, 0x3a, 0x62, 0xfc, 0xcf, 0x9c, 0x4b, 0x45, 0x08, 0x64, 0x03, 0x6f, 0xc6, 0x8b,
	0xf8, 0x15, 0x7e, 0x6f, 0x30, 0xad, 0xed, 0x7f, 0x18, 0xc8, 0x31, 0x29, 0x43, 0x11, 0x48, 0x4e,
	0xca, 0x90, 0x1d, 0x4d, 0xa6, 0x29, 0x6a, 0x96, 0xa8, 0x73, 0xe2, 0xe0, 0x34, 0x27, 0x53, 0x5e,
	0x13, 0x81, 0xe2, 0x81, 0x6a, 0x21, 0xa6, 0x69, 0x52, 0x86, 0x47, 0x3c, 0x8a, 0x44, 0x54, 0xcc,
	0xe8, 0xb2, 0x97, 0x67, 0xca, 0x1a, 0x49, 0xbe, 0x1d, 0x8c, 0x44, 0x0b, 0xb1, 0x14, 0xae, 0x3e,
	0x86, 0x5c, 0xc4, 0xe5, 0x7c, 0xaa, 0xec, 0xcf, 0x60, 0x1e, 0xb5, 0x25, 0x45, 0xc8, 0x0f, 0x52,
	0xa9, 0xe7, 0x78, 0xc2, 0xf6, 0x61, 0xb2, 0x49, 0xe8, 0xa9, 0xb1, 0xf6, 0x31, 0x98, 0xd6, 0xf6,
	0x05, 0x06, 0xe3, 0xae, 0x3b, 0xf9, 0x04, 0x59, 0xb5, 0x08, 0xd3, 0x05, 0x9e, 0x95, 0xde, 0xde,
	0x37, 0x49, 0xaa, 0xba, 0x8b, 0x90, 0x33, 0x5d, 0x93, 0xf8, 0xce, 0xb8, 0x94, 0x9e, 0xcf, 0x77,
	0x06, 0xfb, 0xd0, 0xfe, 0xb8, 0xb3, 0x48, 0x60, 0x62, 0x42, 0xbe, 0xe7, 0x7e, 0x73, 0x3b, 0x3f,
	0x5d, 0x0b, 0x91, 0xa7, 0x60, 0xb8, 0x9d, 0x6e, 0xbf, 0xd9, 0xe9, 0xb9, 0x75, 0x0b, 0x93, 0xe7,
	0x60, 0xb2, 0x46, 0xa5, 0xde, 0x6f, 0x56, 0xda, 0xdf, 0x1b, 0x75, 0x2b, 0x53, 0x1a, 0x02, 0x1c,
	0x9e, 0x99, 0xfc, 0x80, 0xfc, 0x57, 0xae, 0x92, 0x5d, 0xc9, 0xeb, 0x33, 0xa3, 0x9d, 0x9c, 0xee,
	0xc5, 0x9b, 0x07, 0xa8, 0xf4, 0x6c, 0xd5, 0x2f, 0xcb, 0x35, 0x45, 0xab, 0x35, 0x45, 0xdb, 0x35,
	0xc5, 0x7f, 0x63, 0x8a, 0x2f, 0x63, 0x8a, 0xaf, 0x62, 0x8a, 0x97, 0x31, 0xc5, 0xd7, 0x31, 0xc5,
	0x37, 0x31, 0x45, 0xdb, 0x98, 0xe2, 0xff, 0x1b, 0x8a, 0x96, 0x1b, 0x8a, 0x56, 0x1b, 0x8a, 0x7e,
	0xc1, 0xa1, 0xe9, 0xef, 0x9c, 0xfe, 0x52, 0x1f, 0x6e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x79, 0x0c,
	0x84, 0x72, 0x66, 0x02, 0x00, 0x00,
}

func (x ErrorInfo_ErrorType) String() string {
	s, ok := ErrorInfo_ErrorType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *HostConfigRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*HostConfigRequest)
	if !ok {
		that2, ok := that.(HostConfigRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	return true
}
func (this *HostConfigResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*HostConfigResponse)
	if !ok {
		that2, ok := that.(HostConfigResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if that1.Result == nil {
		if this.Result != nil {
			return false
		}
	} else if this.Result == nil {
		return false
	} else if !this.Result.Equal(that1.Result) {
		return false
	}
	return true
}
func (this *HostConfigResponse_File) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*HostConfigResponse_File)
	if !ok {
		that2, ok := that.(HostConfigResponse_File)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.File.Equal(that1.File) {
		return false
	}
	return true
}
func (this *HostConfigResponse_Error) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*HostConfigResponse_Error)
	if !ok {
		that2, ok := that.(HostConfigResponse_Error)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Error.Equal(that1.Error) {
		return false
	}
	return true
}
func (this *FileContent) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FileContent)
	if !ok {
		that2, ok := that.(FileContent)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Content, that1.Content) {
		return false
	}
	if this.Path != that1.Path {
		return false
	}
	return true
}
func (this *ErrorInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ErrorInfo)
	if !ok {
		that2, ok := that.(ErrorInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	if this.Message != that1.Message {
		return false
	}
	return true
}
func (this *HostConfigRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&hostconfig.HostConfigRequest{")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *HostConfigResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&hostconfig.HostConfigResponse{")
	if this.Result != nil {
		s = append(s, "Result: "+fmt.Sprintf("%#v", this.Result)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *HostConfigResponse_File) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&hostconfig.HostConfigResponse_File{` +
		`File:` + fmt.Sprintf("%#v", this.File) + `}`}, ", ")
	return s
}
func (this *HostConfigResponse_Error) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&hostconfig.HostConfigResponse_Error{` +
		`Error:` + fmt.Sprintf("%#v", this.Error) + `}`}, ", ")
	return s
}
func (this *FileContent) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&hostconfig.FileContent{")
	s = append(s, "Content: "+fmt.Sprintf("%#v", this.Content)+",\n")
	s = append(s, "Path: "+fmt.Sprintf("%#v", this.Path)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ErrorInfo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&hostconfig.ErrorInfo{")
	s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	s = append(s, "Message: "+fmt.Sprintf("%#v", this.Message)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringHostconfig(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HostConfigClient is the client API for HostConfig service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HostConfigClient interface {
	GetFile(ctx context.Context, in *HostConfigRequest, opts ...grpc.CallOption) (*HostConfigResponse, error)
}

type hostConfigClient struct {
	cc *grpc.ClientConn
}

func NewHostConfigClient(cc *grpc.ClientConn) HostConfigClient {
	return &hostConfigClient{cc}
}

func (c *hostConfigClient) GetFile(ctx context.Context, in *HostConfigRequest, opts ...grpc.CallOption) (*HostConfigResponse, error) {
	out := new(HostConfigResponse)
	err := c.cc.Invoke(ctx, "/dagger.hostconfig.HostConfig/GetFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostConfigServer is the server API for HostConfig service.
type HostConfigServer interface {
	GetFile(context.Context, *HostConfigRequest) (*HostConfigResponse, error)
}

// UnimplementedHostConfigServer can be embedded to have forward compatible implementations.
type UnimplementedHostConfigServer struct {
}

func (*UnimplementedHostConfigServer) GetFile(ctx context.Context, req *HostConfigRequest) (*HostConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFile not implemented")
}

func RegisterHostConfigServer(s *grpc.Server, srv HostConfigServer) {
	s.RegisterService(&_HostConfig_serviceDesc, srv)
}

func _HostConfig_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostConfigServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dagger.hostconfig.HostConfig/GetFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostConfigServer).GetFile(ctx, req.(*HostConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HostConfig_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dagger.hostconfig.HostConfig",
	HandlerType: (*HostConfigServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFile",
			Handler:    _HostConfig_GetFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hostconfig.proto",
}

func (m *HostConfigRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HostConfigRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HostConfigRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintHostconfig(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *HostConfigResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HostConfigResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HostConfigResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Result != nil {
		{
			size := m.Result.Size()
			i -= size
			if _, err := m.Result.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *HostConfigResponse_File) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HostConfigResponse_File) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.File != nil {
		{
			size, err := m.File.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintHostconfig(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *HostConfigResponse_Error) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HostConfigResponse_Error) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Error != nil {
		{
			size, err := m.Error.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintHostconfig(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *FileContent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FileContent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FileContent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Path) > 0 {
		i -= len(m.Path)
		copy(dAtA[i:], m.Path)
		i = encodeVarintHostconfig(dAtA, i, uint64(len(m.Path)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Content) > 0 {
		i -= len(m.Content)
		copy(dAtA[i:], m.Content)
		i = encodeVarintHostconfig(dAtA, i, uint64(len(m.Content)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ErrorInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ErrorInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ErrorInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintHostconfig(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0x12
	}
	if m.Type != 0 {
		i = encodeVarintHostconfig(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintHostconfig(dAtA []byte, offset int, v uint64) int {
	offset -= sovHostconfig(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *HostConfigRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovHostconfig(uint64(l))
	}
	return n
}

func (m *HostConfigResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Result != nil {
		n += m.Result.Size()
	}
	return n
}

func (m *HostConfigResponse_File) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.File != nil {
		l = m.File.Size()
		n += 1 + l + sovHostconfig(uint64(l))
	}
	return n
}
func (m *HostConfigResponse_Error) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Error != nil {
		l = m.Error.Size()
		n += 1 + l + sovHostconfig(uint64(l))
	}
	return n
}
func (m *FileContent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Content)
	if l > 0 {
		n += 1 + l + sovHostconfig(uint64(l))
	}
	l = len(m.Path)
	if l > 0 {
		n += 1 + l + sovHostconfig(uint64(l))
	}
	return n
}

func (m *ErrorInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovHostconfig(uint64(m.Type))
	}
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovHostconfig(uint64(l))
	}
	return n
}

func sovHostconfig(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozHostconfig(x uint64) (n int) {
	return sovHostconfig(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *HostConfigRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&HostConfigRequest{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`}`,
	}, "")
	return s
}
func (this *HostConfigResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&HostConfigResponse{`,
		`Result:` + fmt.Sprintf("%v", this.Result) + `,`,
		`}`,
	}, "")
	return s
}
func (this *HostConfigResponse_File) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&HostConfigResponse_File{`,
		`File:` + strings.Replace(fmt.Sprintf("%v", this.File), "FileContent", "FileContent", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *HostConfigResponse_Error) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&HostConfigResponse_Error{`,
		`Error:` + strings.Replace(fmt.Sprintf("%v", this.Error), "ErrorInfo", "ErrorInfo", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *FileContent) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&FileContent{`,
		`Content:` + fmt.Sprintf("%v", this.Content) + `,`,
		`Path:` + fmt.Sprintf("%v", this.Path) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ErrorInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ErrorInfo{`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`Message:` + fmt.Sprintf("%v", this.Message) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringHostconfig(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *HostConfigRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHostconfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HostConfigRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HostConfigRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHostconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHostconfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHostconfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHostconfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHostconfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HostConfigResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHostconfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HostConfigResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HostConfigResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field File", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHostconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHostconfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthHostconfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &FileContent{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Result = &HostConfigResponse_File{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHostconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHostconfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthHostconfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ErrorInfo{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Result = &HostConfigResponse_Error{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHostconfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHostconfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FileContent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHostconfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FileContent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FileContent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Content", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHostconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthHostconfig
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthHostconfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Content = append(m.Content[:0], dAtA[iNdEx:postIndex]...)
			if m.Content == nil {
				m.Content = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Path", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHostconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHostconfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHostconfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Path = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHostconfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHostconfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ErrorInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHostconfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ErrorInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ErrorInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHostconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= ErrorInfo_ErrorType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHostconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHostconfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHostconfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHostconfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHostconfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipHostconfig(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowHostconfig
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHostconfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHostconfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthHostconfig
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupHostconfig
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthHostconfig
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthHostconfig        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowHostconfig          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupHostconfig = fmt.Errorf("proto: unexpected end of group")
)
