package io.dagger.groovy.transform

/**
 * Generates the complete Entrypoint.java source as a string from structured metadata.
 * The generated code follows the exact same contract as the Java SDK annotation processor.
 */
class DaggerEntrypointGenerator {

    // ---- Data classes ----

    static class ObjectMeta {
        String name
        String qualifiedName
        String description
        List<FunctionMeta> functions = []
        List<FieldMeta> fields = []
        ConstructorMeta constructor
        boolean isMainObject
    }

    static class FunctionMeta {
        String name
        String methodName
        String description
        String returnType
        List<ParameterMeta> parameters = []
        boolean isCheck = false
        boolean isGenerator = false
        boolean isUp = false
    }

    static class ParameterMeta {
        String name
        String description
        String type
        boolean optional = false
        String defaultValue
        String defaultPath
        String[] ignore
    }

    static class FieldMeta {
        String name
        String description
        String type
    }

    static class ConstructorMeta {
        String description
        List<ParameterMeta> parameters = []
    }

    static class EnumMeta {
        String name
        String description
        List<EnumValueMeta> values = []
    }

    static class EnumValueMeta {
        String value
        String description
    }

    /**
     * Generates the complete Entrypoint.java source code.
     */
    static String generate(String moduleDescription, List<ObjectMeta> objects, List<EnumMeta> enums) {
        StringBuilder sb = new StringBuilder()

        sb.append('// This class has been generated by dagger-java-sdk. DO NOT EDIT.\n')
        sb.append('package io.dagger.gen.entrypoint;\n\n')

        // Imports
        sb.append('import static io.dagger.client.Dagger.dag;\n\n')
        generateImports(sb, objects, enums)

        sb.append('\npublic class Entrypoint {\n')
        sb.append('  Entrypoint() {}\n\n')

        // main method
        generateMainMethod(sb)
        sb.append('\n')

        // dispatch method
        generateDispatchMethod(sb)
        sb.append('\n')

        // register method
        generateRegisterMethod(sb, moduleDescription, objects, enums)
        sb.append('\n')

        // invoke method
        generateInvokeMethod(sb, objects)

        sb.append('}\n')

        return sb.toString()
    }

    private static void generateImports(StringBuilder sb, List<ObjectMeta> objects, List<EnumMeta> enums) {
        Set<String> imports = new TreeSet<>()

        // Always needed
        imports.addAll([
            'io.dagger.client.Changeset',
            'io.dagger.client.Container',
            'io.dagger.client.Directory',
            'io.dagger.client.Function',
            'io.dagger.client.FunctionCall',
            'io.dagger.client.FunctionCallArgValue',
            'io.dagger.client.JSON',
            'io.dagger.client.JsonConverter',
            'io.dagger.client.Module',
            'io.dagger.client.ModuleID',
            'io.dagger.client.Platform',
            'io.dagger.client.TypeDef',
            'io.dagger.client.TypeDefKind',
            'io.dagger.client.exception.DaggerExecException',
            'io.dagger.client.exception.DaggerQueryException',
            'io.dagger.client.telemetry.Telemetry',
            'java.lang.Class',
            'java.lang.Error',
            'java.lang.Exception',
            'java.lang.Integer',
            'java.lang.InterruptedException',
            'java.lang.String',
            'java.lang.Void',
            'java.lang.reflect.InvocationTargetException',
            'java.util.Arrays',
            'java.util.HashMap',
            'java.util.List',
            'java.util.Map',
            'java.util.Objects',
            'java.util.Optional',
            'java.util.concurrent.ExecutionException',
        ])

        // Import user-defined object classes
        for (ObjectMeta obj : objects) {
            imports.add(obj.qualifiedName)
        }

        for (String imp : imports) {
            sb.append("import ${imp};\n")
        }
    }

    private static void generateMainMethod(StringBuilder sb) {
        sb.append('  public static void main(String[] args) throws Exception {\n')
        sb.append('    try (Telemetry telemetry = new Telemetry()) {\n')
        sb.append('      new Entrypoint().dispatch(dag().currentFunctionCall());\n')
        sb.append('    } finally {\n')
        sb.append('      dag().close();\n')
        sb.append('    }\n')
        sb.append('  }\n')
    }

    private static void generateDispatchMethod(StringBuilder sb) {
        sb.append('  private Void dispatch(FunctionCall fnCall) throws Exception {\n')
        sb.append('    try {\n')
        sb.append('      String parentName = fnCall.parentName();\n')
        sb.append('      String fnName = fnCall.name();\n')
        sb.append('      JSON parentJson = fnCall.parent();\n')
        sb.append('      List<FunctionCallArgValue> fnArgs = fnCall.inputArgs();\n')
        sb.append('      Map<String, JSON> inputArgs = new HashMap<>();\n')
        sb.append('      for (FunctionCallArgValue fnArg : fnArgs) {\n')
        sb.append('        inputArgs.put(fnArg.name(), fnArg.value());\n')
        sb.append('      }\n')
        sb.append('\n')
        sb.append('      JSON result;\n')
        sb.append('      if (parentName.isEmpty()) {\n')
        sb.append('        ModuleID modID = register();\n')
        sb.append('        result = JsonConverter.toJSON(modID);\n')
        sb.append('      } else {\n')
        sb.append('        result = invoke(parentJson, parentName, fnName, inputArgs);\n')
        sb.append('      }\n')
        sb.append('\n')
        sb.append('      fnCall.returnValue(result);\n')
        sb.append('      return null;\n')
        sb.append('    } catch (InvocationTargetException e) {\n')
        sb.append('      fnCall.returnError(dag().error(e.getTargetException().getMessage()));\n')
        sb.append('      throw e;\n')
        sb.append('    } catch (DaggerExecException e) {\n')
        sb.append('      fnCall.returnError(dag().error(e.getMessage())')
        sb.append('.withValue("stdout", JsonConverter.toJSON(e.getStdOut()))')
        sb.append('.withValue("stderr", JsonConverter.toJSON(e.getStdErr()))')
        sb.append('.withValue("cmd", JsonConverter.toJSON(e.getCmd()))')
        sb.append('.withValue("exitCode", JsonConverter.toJSON(e.getExitCode()))')
        sb.append('.withValue("path", JsonConverter.toJSON(e.getPath())));\n')
        sb.append('      throw e;\n')
        sb.append('    } catch (Exception e) {\n')
        sb.append('      fnCall.returnError(dag().error(e.getMessage()));\n')
        sb.append('      throw e;\n')
        sb.append('    }\n')
        sb.append('  }\n')
    }

    private static void generateRegisterMethod(StringBuilder sb, String moduleDescription,
                                                 List<ObjectMeta> objects, List<EnumMeta> enums) {
        sb.append('  private ModuleID register()\n')
        sb.append('      throws ExecutionException, DaggerQueryException, InterruptedException {\n')

        sb.append('    Module module = dag().module()')
        if (moduleDescription != null && !moduleDescription.isBlank()) {
            sb.append(".withDescription(${quote(moduleDescription)})")
        }

        for (ObjectMeta obj : objects) {
            sb.append('.withObject(dag()\n')
            sb.append('        .typeDef()')
            sb.append(".withObject(${quote(obj.name)}")
            if (obj.description != null && !obj.description.isBlank()) {
                sb.append(",\n            new TypeDef.WithObjectArguments()")
                sb.append(".withDescription(${quote(obj.description)})")
            }
            sb.append(')')  // end of withObject(

            // Functions
            for (FunctionMeta fn : obj.functions) {
                sb.append("\n        .withFunction(")
                generateWithFunction(sb, fn, obj.name)
                sb.append(')')
            }

            // Fields
            for (FieldMeta field : obj.fields) {
                sb.append("\n        .withField(${quote(field.name)}, ")
                sb.append(DaggerTypeMapper.toDaggerTypeDef(field.type))
                if (field.description != null && !field.description.isBlank()) {
                    sb.append(",\n            new TypeDef.WithFieldArguments()")
                    sb.append(".withDescription(${quote(field.description)})")
                }
                sb.append(')')
            }

            // Constructor
            if (obj.constructor != null) {
                sb.append("\n        .withConstructor(")
                generateWithConstructor(sb, obj)
                sb.append(')')
            }

            sb.append(')')  // end of .withObject(
        }

        // Enums
        for (EnumMeta enumMeta : enums) {
            sb.append('.withEnum(dag().typeDef()\n')
            sb.append("        .withEnum(${quote(enumMeta.name)}")
            if (enumMeta.description != null && !enumMeta.description.isBlank()) {
                sb.append(", new TypeDef.WithEnumArguments()")
                sb.append(".withDescription(${quote(enumMeta.description)})")
            }
            sb.append(')')  // end of withEnum(

            for (EnumValueMeta ev : enumMeta.values) {
                sb.append("\n        .withEnumValue(${quote(ev.value)}")
                if (ev.description != null && !ev.description.isBlank()) {
                    sb.append(",\n            new TypeDef.WithEnumValueArguments()")
                    sb.append(".withDescription(${quote(ev.description)})")
                }
                sb.append(')')
            }

            sb.append(')')  // end of .withEnum(
        }

        sb.append(';\n')
        sb.append('    return module.id();\n')
        sb.append('  }\n')
    }

    private static void generateWithFunction(StringBuilder sb, FunctionMeta fn, String objectName) {
        String returnTypeDef = DaggerTypeMapper.toDaggerTypeDef(fn.returnType)
        sb.append("\n            dag().function(${quote(fn.name)}, ${returnTypeDef})")

        if (fn.description != null && !fn.description.isBlank()) {
            sb.append("\n                .withDescription(${quote(fn.description)})")
        }

        if (fn.isCheck) {
            sb.append("\n                .withCheck()")
        }

        if (fn.isGenerator) {
            sb.append("\n                .withGenerator()")
        }

        if (fn.isUp) {
            sb.append("\n                .withUp()")
        }

        for (ParameterMeta param : fn.parameters) {
            sb.append("\n                .withArg(${quote(param.name)}, ")
            sb.append(DaggerTypeMapper.toDaggerTypeDef(param.type))
            if (param.optional) {
                sb.append('.withOptional(true)')
            }

            boolean hasDescription = param.description != null && !param.description.isBlank()
            boolean hasDefaultValue = param.defaultValue != null
            boolean hasDefaultPath = param.defaultPath != null
            boolean hasIgnore = param.ignore != null

            if (hasDescription || hasDefaultValue || hasDefaultPath || hasIgnore) {
                sb.append(",\n                    new Function.WithArgArguments()")
                if (hasDescription) {
                    sb.append(".withDescription(${quote(param.description)})")
                }
                if (hasDefaultValue) {
                    sb.append(".withDefaultValue(JSON.from(${quote(param.defaultValue)}))")
                }
                if (hasDefaultPath) {
                    sb.append(".withDefaultPath(${quote(param.defaultPath)})")
                }
                if (hasIgnore) {
                    sb.append('.withIgnore(List.of(')
                    sb.append(param.ignore.collect { quote(it) }.join(', '))
                    sb.append('))')
                }
            }
            sb.append(')')  // end of .withArg(
        }
    }

    private static void generateWithConstructor(StringBuilder sb, ObjectMeta obj) {
        ConstructorMeta ctor = obj.constructor
        sb.append("dag().function(\"\", ${DaggerTypeMapper.toDaggerTypeDef(obj.qualifiedName)})")

        if (ctor.description != null && !ctor.description.isBlank()) {
            sb.append("\n                .withDescription(${quote(ctor.description)})")
        }

        for (ParameterMeta param : ctor.parameters) {
            sb.append("\n                .withArg(${quote(param.name)}, ")
            sb.append(DaggerTypeMapper.toDaggerTypeDef(param.type))
            if (param.optional) {
                sb.append('.withOptional(true)')
            }

            boolean hasDescription = param.description != null && !param.description.isBlank()
            boolean hasDefaultValue = param.defaultValue != null
            boolean hasDefaultPath = param.defaultPath != null
            boolean hasIgnore = param.ignore != null

            if (hasDescription || hasDefaultValue || hasDefaultPath || hasIgnore) {
                sb.append(",\n                    new Function.WithArgArguments()")
                if (hasDescription) {
                    sb.append(".withDescription(${quote(param.description)})")
                }
                if (hasDefaultValue) {
                    sb.append(".withDefaultValue(JSON.from(${quote(param.defaultValue)}))")
                }
                if (hasDefaultPath) {
                    sb.append(".withDefaultPath(${quote(param.defaultPath)})")
                }
                if (hasIgnore) {
                    sb.append('.withIgnore(List.of(')
                    sb.append(param.ignore.collect { quote(it) }.join(', '))
                    sb.append('))')
                }
            }
            sb.append(')')  // end of .withArg(
        }
    }

    private static void generateInvokeMethod(StringBuilder sb, List<ObjectMeta> objects) {
        sb.append('  private JSON invoke(JSON parentJson, String parentName, String fnName,\n')
        sb.append('      Map<String, JSON> inputArgs) throws Exception {\n')

        boolean firstObj = true
        for (ObjectMeta obj : objects) {
            if (firstObj) {
                sb.append("    if (parentName.equals(${quote(obj.name)})) {\n")
                firstObj = false
            } else {
                sb.append(" else if (parentName.equals(${quote(obj.name)})) {\n")
            }

            String simpleClassName = obj.qualifiedName.substring(obj.qualifiedName.lastIndexOf('.') + 1)
            boolean hasConstructor = obj.constructor != null

            boolean firstFn = true
            for (FunctionMeta fn : obj.functions) {
                if (firstFn) {
                    sb.append("      if (fnName.equals(${quote(fn.name)})) {\n")
                    firstFn = false
                } else {
                    sb.append(" else if (fnName.equals(${quote(fn.name)})) {\n")
                }

                generateFunctionInvoke(sb, obj, fn, simpleClassName, hasConstructor)

                sb.append('      }')
            }

            // Constructor handling
            if (hasConstructor) {
                if (firstFn) {
                    sb.append("      if (fnName.equals(\"\")) {\n")
                    firstFn = false
                } else {
                    sb.append("\n      if (fnName.equals(\"\")) {\n")
                }
                generateConstructorInvoke(sb, obj, simpleClassName)
                sb.append('      }\n')
            } else if (!firstFn) {
                sb.append('\n')
            }

            sb.append('    }')
        }
        sb.append('\n')
        sb.append('    throw new InvocationTargetException(new Error("unknown function " + fnName));\n')
        sb.append('  }\n')
    }

    private static void generateFunctionInvoke(StringBuilder sb, ObjectMeta obj, FunctionMeta fn,
                                                 String simpleClassName, boolean hasConstructor) {
        // Object deserialization: if there's a constructor, inline it per function; otherwise shared above
        if (hasConstructor) {
            sb.append("        Class clazz = Class.forName(${quote(obj.qualifiedName)});\n")
            sb.append("        ${simpleClassName} obj = (${simpleClassName}) JsonConverter.fromJSON(parentJson, clazz);\n")
        } else {
            sb.append("        Class clazz = Class.forName(${quote(obj.qualifiedName)});\n")
            sb.append("        ${simpleClassName} obj = (${simpleClassName}) JsonConverter.fromJSON(parentJson, clazz);\n")
        }

        // Parameter deserialization
        for (ParameterMeta param : fn.parameters) {
            String javaType = DaggerTypeMapper.toJavaType(param.type)
            String defaultVal = DaggerTypeMapper.defaultValue(param.type)
            String classLiteral = DaggerTypeMapper.toClassLiteral(param.type)
            boolean isList = DaggerTypeMapper.isList(param.type)

            sb.append("        ${javaType} ${param.name} = ${defaultVal};\n")
            sb.append("        if (inputArgs.get(${quote(param.name)}) != null) {\n")

            if (isList) {
                sb.append("          ${param.name} = Arrays.asList(JsonConverter.fromJSON(inputArgs.get(${quote(param.name)}), ${classLiteral}));\n")
            } else {
                sb.append("          ${param.name} = JsonConverter.fromJSON(inputArgs.get(${quote(param.name)}), ${classLiteral});\n")
            }

            sb.append('        }\n')

            if (param.optional) {
                sb.append("        var ${param.name}_opt = Optional.ofNullable(${param.name});\n")
            } else if (!DaggerTypeMapper.isPrimitive(param.type)) {
                sb.append("        Objects.requireNonNull(${param.name}, ${quote("${param.name} must not be null")});\n")
            }
        }

        // Method invocation
        boolean returnsVoid = fn.returnType == null || fn.returnType == 'void'
        String javaReturnType = DaggerTypeMapper.toJavaType(fn.returnType)

        // Build parameter list for invocation
        String paramList = fn.parameters.collect { p ->
            p.optional ? "${p.name}_opt" : p.name
        }.join(', ')

        if (returnsVoid) {
            sb.append("        obj.${fn.methodName}(${paramList});\n")
            sb.append('        return JsonConverter.toJSON(null);\n')
        } else {
            sb.append("        ${javaReturnType} res = obj.${fn.methodName}(${paramList});\n")
            sb.append('        return JsonConverter.toJSON(res);\n')
        }
    }

    private static void generateConstructorInvoke(StringBuilder sb, ObjectMeta obj, String simpleClassName) {
        ConstructorMeta ctor = obj.constructor

        for (ParameterMeta param : ctor.parameters) {
            String javaType = DaggerTypeMapper.toJavaType(param.type)
            String defaultVal = DaggerTypeMapper.defaultValue(param.type)
            String classLiteral = DaggerTypeMapper.toClassLiteral(param.type)
            boolean isList = DaggerTypeMapper.isList(param.type)

            sb.append("        ${javaType} ${param.name} = ${defaultVal};\n")
            sb.append("        if (inputArgs.get(${quote(param.name)}) != null) {\n")

            if (isList) {
                sb.append("          ${param.name} = Arrays.asList(JsonConverter.fromJSON(inputArgs.get(${quote(param.name)}), ${classLiteral}));\n")
            } else {
                sb.append("          ${param.name} = JsonConverter.fromJSON(inputArgs.get(${quote(param.name)}), ${classLiteral});\n")
            }

            sb.append('        }\n')

            if (param.optional) {
                sb.append("        var ${param.name}_opt = Optional.ofNullable(${param.name});\n")
            } else if (!DaggerTypeMapper.isPrimitive(param.type)) {
                sb.append("        Objects.requireNonNull(${param.name}, ${quote("${param.name} must not be null")});\n")
            }
        }

        String paramList = ctor.parameters.collect { p ->
            p.optional ? "${p.name}_opt" : p.name
        }.join(', ')

        sb.append("        ${simpleClassName} res = new ${simpleClassName}(${paramList});\n")
        sb.append('        return JsonConverter.toJSON(res);\n')
    }

    /**
     * Escapes and quotes a string for Java source code.
     */
    private static String quote(String s) {
        if (s == null) return 'null'
        String escaped = s.replace('\\', '\\\\')
                          .replace('"', '\\"')
                          .replace('\n', '\\n')
                          .replace('\r', '\\r')
                          .replace('\t', '\\t')
        return "\"${escaped}\""
    }
}
